---
- name: replace pentaho/WEB-INF/web.xml and log4j.xml
  template: >
    src={{ item }}.j2
    dest={{ pentahobi_base_dir }}/{{ item }}
  with_items:
    - webapps/pentaho/WEB-INF/web.xml
    - webapps/pentaho/WEB-INF/classes/log4j.xml

- name: ensure directories
  file: >
    state=directory
    path={{ pentahobi_solution_path }}/system/{{ item }}
    owner={{ pentahobi_user }}
    group={{ pentahobi_group }}
    mode=0755
  with_items:
    - hibernate
    - jackrabbit

- name: copy configuration files
  copy: >
    src=system/{{ item }}
    dest={{ pentahobi_solution_path }}/system/{{ item }}
    owner={{ pentahobi_user }}
    group={{ pentahobi_group }}
  with_items:
    - applicationContext-spring-security-jdbc.xml
    - hibernate/hibernate-settings.xml
    - hibernate/postgresql.jndi.hibernate.cfg.xml
    - jackrabbit/repository.xml
  notify: restart tomcat

- name: copy configuration files
  template: >
    src=system/{{ item }}.j2
    dest={{ pentahobi_solution_path }}/system/{{ item }}
    owner={{ pentahobi_user }}
    group={{ pentahobi_group }}
  with_items:
    - smtp-email/email_config.xml
    - applicationContext-security-ldap.properties
  notify: restart tomcat

- name: set authentication provider
  copy: >
    content="provider={{ pentabobi_auth_provider }}\n"
    dest={{ pentahobi_solution_path }}/system/security.properties
  notify: restart tomcat
